### PR TITLE
Add 18 new virtual-keys and support for them on Linux

### PR DESCRIPTION
**Pull request by shiftee**
This PR adds support for keys needed to edit scripts and C/C++ code remotely.

I picked key values that seemed to be unused, let me know if they should be changed.

This should probably be tested to make sure it does not break other operating systems

### CODE REVIEW

**Comment by YiannisBourkelis** [comment]
@shiftee I used the virtual key codes from windows based on this link: [https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx](https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx) (Virtual-Key Codes)
With your notifications do these special keys work well on linux? Have you tested them?

**Comment by shiftee** [comment]
I have tested the new keys and they all work from one Ubuntu machine to another.

If someone could test the changes on windows/mac to check nothing is broken.
I imagine it wouldn't be difficult to add support for the new keys on mac, not sure about windows

**Comment by YiannisBourkelis** [comment]
@shiftee ok I will merge the pr and add a todo for windows and OS X to ignore these special keys at the moment.

**Comment by shiftee** [comment]
Thanks

**Pull request merged**
